# Generated by Django 3.2.9 on 2021-12-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_submission_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='choice_id',
            field=models.IntegerField(),
        ),
    ]
